### ISSUE TITLE
Atheris 2.2.2 fails to instrument a while loop in Python 3.11.0

### ISSUE THREAD

**Issue by charfa** [google/atheris#57]
Trying to instrument function like this fails with an assertion error in `check_state` on Python 3.11:
```python
def foo(data):
    while data:
        pass
```

Interestingly, a function like this instruments correctly:
```python
def foo(data):
    while False:
        pass
```

Full reproduction:
```
~/tmp/python/mylib$ python --version
Python 3.11.0
~/tmp/python/mylib$ pip list
Package    Version
---------- -------
atheris    2.2.2
pip        23.0.1
setuptools 65.5.0
~/tmp/python/mylib$ cat foo.py 
import atheris


@atheris.instrument_func
def foo(data):
    while data:
        pass
~/tmp/python/mylib$ python foo.py 
Traceback (most recent call last):
  File "~/tmp/python/mylib/foo.py", line 4, in <module>
    @atheris.instrument_func
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/tmp/lib/python3.11/site-packages/atheris/instrument_bytecode.py", line 886, in instrument_func
    func.__code__ = patch_code(func.__code__, True, True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/tmp/lib/python3.11/site-packages/atheris/instrument_bytecode.py", line 878, in patch_code
    return inst.to_code()
           ^^^^^^^^^^^^^^
  File "~/.pyenv/versions/tmp/lib/python3.11/site-packages/atheris/instrument_bytecode.py", line 529, in to_code
    self._check_state()
  File "~/.pyenv/versions/tmp/lib/python3.11/site-packages/atheris/instrument_bytecode.py", line 435, in _check_state
    listing[i].check_state()
  File "~/.pyenv/versions/tmp/lib/python3.11/site-packages/atheris/instrument_bytecode.py", line 236, in check_state
    assert (
AssertionError
```

**Comment by charfa** [comment]
Does not reproduce on python 3.10.8
