### ISSUE TITLE
How could I save crash log？

### ISSUE THREAD

**Issue by JerryHuang-h** [google/atheris#66]
what should I do to save the crash log？

**Comment by jvoisin** [comment]
Redirect the output to a file?

**Comment by JerryHuang-h** [comment]
> Redirect the output to a file?

I had Redirect the stdout and stderr like 
`p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, bufsize=0, cwd=cmd_path, preexec_fn=os.setsid)`, 
and write to a file. However, I got something has wrong order, like 
`=== Uncaught Python exception: ===
ValueError: could not convert string to float: '.'
Traceback (most recent call last):
File "yaml_fuzzer.py", line 49, in TestOneInput
for _ in iterator:
File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/main.py", line 452, in load_all
yield constructor.get_data()
File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 107, in get_data
return self.construct_document(self.composer.get_node())
File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 117, in construct_document
data = self.construct_object(node)
File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 144, in construct_object
data = self.construct_non_recursive_object(node)
File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 178, in construct_non_recursive_object
data = constructor(self, node)
File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 494, in construct_yaml_float
return sign * float(value_s)
ValueError: could not convert string to float: '.'

Input was <class 'str'>: ._
Codepoints: ['0x2e', '0x5f']==78== ERROR: libFuzzer: fuzz target exited
SUMMARY: libFuzzer: fuzz target exited
MS: 4 CrossOver-ChangeBinInt-CMP-EraseBytes- DE: "\012_"-; base unit: 2711ff63ab10404117287c8a3c4b734cc65e7a50
0xfb,0x2e,0x5f,
\373._
artifact_prefix='fuzz_regisstry_'; Test unit written to fuzz_regisstry_crash-2c2c3428457c025d4be699272d44a27826eece25
Base64: +y5f
`
For some reason, I can't redirect stdout and stderr separately. If there Atheris has a parameter to save the crash log or do this by itself as well as crash sample?Thanks!

**Comment by jvoisin** [comment]
I don't think there is a parameter for this, no.

**Comment by JerryHuang-h** [comment]
> I don't think there is a parameter for this, no.

How about future?

**Comment by jvoisin** [comment]
Feel free to open a pull-request :)

**Comment by JerryHuang-h** [comment]
set os.environ['PYTHONUNBUFFERED'] = '1' before Popen can resolve this problem.
